/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jets.paintv2;

import com.paint.Circle;
import com.paint.FreeLine;
import com.paint.Line;
import com.paint.Pattern;
import com.paint.Points;
import com.paint.Rect;
import java.awt.Checkbox;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JColorChooser;

/**
 *
 * @author Sara
 */
public class PaintApp extends javax.swing.JPanel {
    Checkbox fill;
    Color fontColor=Color.black ;
    Graphics go;
    int x,y,x2,y2;
    int pressedFlag=0;
    int i=0,index=0;
    int Erase=0,clear=0;
    int xErase,yErase;
    int undo=0;
    int polycount=2;
    boolean filled=false;
    Vector<Pattern>  currentShape;
    Vector<Pattern> shapes;
  //  ArrayList<Integer> xpolys;
  //  ArrayList<Integer> ypolys;
    /**
     * Creates new form PaintApp
     */
    public PaintApp() {
        this.shapes = new Vector<>();
        this.currentShape=new Vector<>();
        initComponents();
        choice1.add("Line");
        choice1.add("Circle");
        choice1.add("Rect");
        choice1.add("Free line");
        //panel1.setOpaque(true);
      
        this.addKeyListener(new KeyListener(){

            @Override
            public void keyTyped(KeyEvent e) {
                System.out.println(e.getSource());
                System.out.println(e.VK_ADD );
            }

            @Override
            public void keyPressed(KeyEvent e) {
               System.out.println(e.getSource());
               // System.out.println(e.VK_ADD );
            }

            @Override
            public void keyReleased(KeyEvent e) {
               System.out.println(e.getSource());
                System.out.println(e.VK_ADD );
            }
        
        
        });
        this.addMouseMotionListener(
			new MouseAdapter(){
				public void mouseDragged(MouseEvent ev){	
					if(pressedFlag==1 && isInBoreder(ev) ){
						x2=ev.getX();
						y2=ev.getY();
						repaint();
					}
                                        if(index==3){
                                            shapes.add(new Points(x2, y2,fontColor));
                                            repaint();
                                        }
                                        if(Erase==1 && pressedFlag==1 &&y2>45 &&y>45){
                                             shapes.add(new Rect(x2-8, y2-8,12,12,Color.white,true));
                                             xErase=ev.getX();
                                             yErase=ev.getY();
                                             repaint();
                                        }                                       
				}
                               public void mouseMoved(MouseEvent e){
                               
                                    if(Erase==1&&y2>45 &&y>45){
                                            xErase=e.getX();
                                            yErase=e.getY();
                                             repaint();
                                        }
                               }
			}
		);
		this.addMouseListener(new PaintApp.MypressedListener ());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        checkbox1 = new java.awt.Checkbox();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();

        setBackground(new java.awt.Color(255, 255, 255));

        choice1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice1ItemStateChanged(evt);
            }
        });

        checkbox1.setLabel("Fill");
        checkbox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox1ItemStateChanged(evt);
            }
        });

        label1.setBackground(new java.awt.Color(0, 0, 0));
        label1.setText("   .");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });

        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setText("Undo");
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label2MouseExited(evt);
            }
        });

        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setText("Redo");
        label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label3MouseExited(evt);
            }
        });

        label4.setBackground(new java.awt.Color(255, 255, 255));
        label4.setText("Eraser");
        label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label4MouseExited(evt);
            }
        });

        label5.setForeground(new java.awt.Color(255, 51, 51));
        label5.setText("Clear");
        label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(275, 275, 275))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void label4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseExited

        label4.setBackground(Color.white);
    }//GEN-LAST:event_label4MouseExited

    private void label4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseEntered

        label4.setBackground(Color.yellow);
    }//GEN-LAST:event_label4MouseEntered

    private void label4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseClicked
        // TODO add your handling code here:
        Erase=1;
    }//GEN-LAST:event_label4MouseClicked

    private void label3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseExited
        // TODO add your handling code here:
        label3.setBackground(Color.white);
    }//GEN-LAST:event_label3MouseExited

    private void label3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseEntered
        // TODO add your handling code here:
        label3.setBackground(Color.yellow);
    }//GEN-LAST:event_label3MouseEntered

    private void label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseClicked
        // Redo
        Erase=0;
        if(currentShape.size()>0){
            shapes.add(currentShape.lastElement());
            currentShape.remove(currentShape.lastElement());
            //undo=0;
            repaint();
        }
    }//GEN-LAST:event_label3MouseClicked

    private void label2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseExited
        // TODO add your handling code here:
        label2.setBackground(Color.white);
    }//GEN-LAST:event_label2MouseExited

    private void label2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseEntered
        // TODO add your handling code here:
        label2.setBackground(Color.yellow);
    }//GEN-LAST:event_label2MouseEntered

    private void label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseClicked
        // Undo
        Erase=0;
        if(shapes.size()>0){
            currentShape.add(shapes.lastElement());
            shapes.remove(currentShape.lastElement());
            undo=1;
            repaint();
        }
    }//GEN-LAST:event_label2MouseClicked

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        // choose color
        fontColor = JColorChooser.showDialog(PaintApp.this, "Choose a color", Color.blue);
        label1.setBackground(fontColor);
    }//GEN-LAST:event_label1MouseClicked

    private void choice1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice1ItemStateChanged
        // choose shape
        Erase=0;
        undo=0;
        index=choice1.getSelectedIndex();
    }//GEN-LAST:event_choice1ItemStateChanged

    private void checkbox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox1ItemStateChanged
     //  Erase=0;      
       filled=checkbox1.getState();
    }//GEN-LAST:event_checkbox1ItemStateChanged

    private void label5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseClicked
        // TODO add your handling code here:
        clear=1;
        //currentShape=shapes;
       
        shapes.clear();
        repaint();
    }//GEN-LAST:event_label5MouseClicked

protected void paintComponent(Graphics g) {
        super.paintComponent(g);
    
        DrawToolBar(g,1);
        for(Pattern s:shapes){
            s.drawShape(g);
	}
        if(Erase==1 &&y2>45&&undo==0 ){
            g.setColor(Color.white);
            g.fillRect(x2-4, y2-4,8,8); 
            g.setColor(Color.BLACK);
            g.draw3DRect(xErase-8, yErase-8,12,12,true);
        }else if(y>50 &&undo==0 &&Erase==0 && pressedFlag==1 ){
                g.setColor(fontColor);
                switch(index){
                        case 0:
                             g.drawLine(x,y,x2,y2);                           
                            break;
                        case 1:
                            if(filled){
                                 g.fillOval(x>x2?x2:x, y>y2?y2:y,Math.abs(x2-x),Math.abs(y2-y));
                            }else{
                                 g.drawOval(x>x2?x2:x, y>y2?y2:y,Math.abs(x2-x),Math.abs(y2-y));
                            }
                            break;
                        case 2:
                            if(filled){
                                 g.fillRect(x>x2?x2:x, y>y2?y2:y,Math.abs(x2-x),Math.abs(y2-y));
                            }else{
                                 g.draw3DRect(x>x2?x2:x, y>y2?y2:y,Math.abs(x2-x),Math.abs(y2-y),true);
                            }

                            break;
                        case 3:
                          //  g.fillOval(x2-2, y2-2,3, 3);
                           g.fillRect(x2-1, y2-1,2,2);
                          /* int xs[]=new int[polycount];
                           int ys[]=new int[polycount];
                           xs[0]=x;ys[0]=y;
                          // for(int i=1;i<polycount;i++){
                               xs[i]=x2;
                               ys[i]=y2;
                           //}
                            g.drawPolyline(xs,ys,polycount);
                           */
                            break;
                }
            undo=0;
            clear=0;
        }


}
 public void DrawToolBar(Graphics g,int selected ){
         int x=500,y=5;
         g.setColor(new Color(0,64,128));        
         g.fillRect(0, 0, 2000, 40);
         if(index==0)
            g.setColor(Color.yellow);
         else
            g.setColor(Color.white);
         g.fillRect(10+x, y, 30, 20);  
         if(index==1)
            g.setColor(Color.yellow);
         else
            g.setColor(Color.white);
         g.fillRect(50+x, y, 30, 20); 
         if(index==2)
            g.setColor(Color.yellow);
         else
            g.setColor(Color.white);
         g.fillRect(90+x, y, 30, 20); 
         if(index==3)
            g.setColor(Color.yellow);
         else
            g.setColor(Color.white);
         g.fillRect(130+x, y, 30, 20); 
              
         g.setColor(Color.blue);
         g.drawLine(13+x,y+2,35+x,22);        
         g.drawOval(53+x,y+2,25,15);
         g.draw3DRect(93+x,y+2,22,12,true);
         int xValues2[] = {150+x, 135+x, 160+x};
         int yValues2[] = {10, 15, 20};
         g.drawPolyline(xValues2,yValues2,3 ); 
    }
class MypressedListener extends  MouseAdapter{	
                @Override
		public void mousePressed(MouseEvent ev) { 
                        int xm=500;
			x=ev.getX();
                        y=ev.getY();
                       /* xpolys.add(x);
                        ypolys.add(y);*/
                        if(y>45){
                            pressedFlag=1;                     
                            undo=0;
                        }else if(x>=10+xm && x<=40+xm && y>=5 && y<=25){
                            //line
                            Erase=0;
                            index=0;
                            repaint();

                        }else if(x>=50+xm && x<=80+xm && y>=5 && y<=25){
                            //circle
                            Erase=0;
                            index=1;
                            repaint();
                        }else if(x>=90+xm && x<=120+xm && y>=5 && y<=25){
                            //Rect
                            Erase=0;
                            index=2;
                            repaint();
                        }else if(x>=130+xm && x<=160+xm && y>=5 && y<=25){
                            //FreeLine
                            Erase=0;
                            index=3;
                            repaint();
                        }
		}
                @Override
		public void mouseReleased(MouseEvent ev){
			  if(y>45){
				pressedFlag=0;
                                if(Erase==1){
                                    //shapes.add(new Rect(x2-8, y2-8,12,12,Color.white,true));
                                 }else{
                                    switch(index){
                                      case 0:
                                           shapes.add(new Line(x, y, x2 ,y2,fontColor));
                                          break;
                                      case 1:
                                          shapes.add(new Circle(x>x2?x2:x, y>y2?y2:y,Math.abs(x2-x),Math.abs(y2-y),fontColor,filled));
                                          break;
                                      case 2:

                                          shapes.add(new Rect(x>x2?x2:x, y>y2?y2:y,Math.abs(x2-x),Math.abs(y2-y),fontColor,filled));

                                      case 3:
                                        /*  int xs[]=new int[polycount];
                                           int ys[]=new int[polycount];
                                           xs[0]=x;ys[0]=y;
                                          // for(int i=1;i<polycount;i++){
                                               xs[i]=x2;
                                               ys[i]=y2;
                                               shapes.add(new FreeLine(fontColor, polycount, xs, ys));
                                          */ //}
                                          //  g.drawPolyline(xs,ys,polycount);
                                          break;
                                  }
                                }
                          }
			
                              
				i++;
			
			
		}
	}
    // TODO overwrite start(), stop() and destroy() methods
 public boolean isInBoreder(MouseEvent ev){
     return ev.getX()>2 && ev.getX()<getWidth()-2&& ev.getY()>45 &&ev.getY()<getHeight();
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private java.awt.Choice choice1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables
}
